Settings:
  deleteShopsOnRegionRestore: true
  deleteShopsOnRegionUnsell: false
  ignorePlugins:
    - AShopPlugin
#    - Shopkeepers
#    - QuickShop
#    - ShopChest
#    - UltimateShops
#    - DisplayShops